CREATE TABLE IF NOT EXISTS `bank` (
                        `id` bigint NOT NULL AUTO_INCREMENT,
                        `created_by` VARCHAR(255) DEFAULT NULL,
                        `created_date` datetime(6) DEFAULT NULL,
                        `modified_by` VARCHAR(255) DEFAULT NULL,
                        `modified_date` datetime(6) DEFAULT NULL,
                        `status` VARCHAR(255) DEFAULT NULL,
                        `version` bigint DEFAULT NULL,
                        `name` VARCHAR(255) NOT NULL,
                        `uuid` VARCHAR(255) NOT NULL,
                        `last_modified_by` VARCHAR(255) DEFAULT NULL,
                        `last_modified_date` datetime(6) DEFAULT NULL,
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `UK_ld5hsh9a9d6a849esqbf7d9qm` (`name`),
                        UNIQUE KEY `UKld5hsh9a9d6a849esqbf7d9qm` (`name`),
                        UNIQUE KEY `UK_q0ahw55c3ycfi04456isnleve` (`uuid`),
                        UNIQUE KEY `UKq0ahw55c3ycfi04456isnleve` (`uuid`)
)

CREATE TABLE IF NOT EXISTS `city` (
                        `id` bigint NOT NULL AUTO_INCREMENT,
                        `created_by` VARCHAR(255) DEFAULT NULL,
                        `created_date` datetime(6) DEFAULT NULL,
                        `modified_by` VARCHAR(255) DEFAULT NULL,
                        `modified_date` datetime(6) DEFAULT NULL,
                        `status` VARCHAR(255) DEFAULT NULL,
                        `version` bigint DEFAULT NULL,
                        `name` VARCHAR(255) NOT NULL,
                        `uuid` VARCHAR(255) NOT NULL,
                        `last_modified_by` VARCHAR(255) DEFAULT NULL,
                        `last_modified_date` datetime(6) DEFAULT NULL,
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `UK_qsstlki7ni5ovaariyy9u8y79` (`name`),
                        UNIQUE KEY `UKqsstlki7ni5ovaariyy9u8y79` (`name`),
                        UNIQUE KEY `UK_6f8gspgbkqb8vomjddx13neao` (`uuid`),
                        UNIQUE KEY `UK6f8gspgbkqb8vomjddx13neao` (`uuid`)
)

CREATE TABLE IF NOT EXISTS `customer` (
                            `id` bigint NOT NULL AUTO_INCREMENT,
                            `created_by` VARCHAR(255) DEFAULT NULL,
                            `created_date` datetime(6) DEFAULT NULL,
                            `modified_by` VARCHAR(255) DEFAULT NULL,
                            `modified_date` datetime(6) DEFAULT NULL,
                            `status` VARCHAR(255) DEFAULT NULL,
                            `version` bigint DEFAULT NULL,
                            `account_number` VARCHAR(255) NOT NULL,
                            `address_line1` VARCHAR(255) DEFAULT NULL,
                            `address_line2` VARCHAR(255) DEFAULT NULL,
                            `city` VARCHAR(255) DEFAULT NULL,
                            `country` VARCHAR(255) DEFAULT NULL,
                            `contact_email` VARCHAR(255) DEFAULT NULL,
                            `phone_number` VARCHAR(255) DEFAULT NULL,
                            `telephone_number` VARCHAR(255) DEFAULT NULL,
                            `description` VARCHAR(255) DEFAULT NULL,
                            `image_url` VARCHAR(255) DEFAULT NULL,
                            `name` VARCHAR(255) NOT NULL,
                            `bank_id` bigint DEFAULT NULL,
                            `customer_type_id` bigint DEFAULT NULL,
                            `service_type_id` bigint DEFAULT NULL,
                            `uuid` VARCHAR(255) NOT NULL,
                            `last_modified_by` VARCHAR(255) DEFAULT NULL,
                            `last_modified_date` datetime(6) DEFAULT NULL,
                            PRIMARY KEY (`id`),
                            UNIQUE KEY `UK_kkyy3tr5399btuq307jibrjqm` (`account_number`),
                            UNIQUE KEY `UK_crkjmjk1oj8gb6j6t5kt7gcxm` (`name`),
                            UNIQUE KEY `UKcrkjmjk1oj8gb6j6t5kt7gcxm` (`name`),
                            UNIQUE KEY `UK_q8w2f8xfdoax44qc8w0epholu` (`uuid`),
                            UNIQUE KEY `UKq8w2f8xfdoax44qc8w0epholu` (`uuid`),
                            KEY `FKkegxm9b6vhjh30rgc0tvrk0r7` (`bank_id`),
                            KEY `FKn8vf9jf3m29plqn6rx45p2pl7` (`customer_type_id`),
                            KEY `FKiruk9whc8cplfv6inxvm9g74i` (`service_type_id`),
                            CONSTRAINT `FKiruk9whc8cplfv6inxvm9g74i` FOREIGN KEY (`service_type_id`) REFERENCES `service_type` (`id`),
                            CONSTRAINT `FKkegxm9b6vhjh30rgc0tvrk0r7` FOREIGN KEY (`bank_id`) REFERENCES `bank` (`id`),
                            CONSTRAINT `FKn8vf9jf3m29plqn6rx45p2pl7` FOREIGN KEY (`customer_type_id`) REFERENCES `customer_type` (`id`)
)

CREATE TABLE IF NOT EXISTS `customer_branch` (
                                   `id` bigint NOT NULL AUTO_INCREMENT,
                                   `created_by` VARCHAR(255) DEFAULT NULL,
                                   `created_date` datetime(6) DEFAULT NULL,
                                   `modified_by` VARCHAR(255) DEFAULT NULL,
                                   `modified_date` datetime(6) DEFAULT NULL,
                                   `status` VARCHAR(255) DEFAULT NULL,
                                   `version` bigint DEFAULT NULL,
                                   `address_line1` VARCHAR(255) DEFAULT NULL,
                                   `address_line2` VARCHAR(255) DEFAULT NULL,
                                   `city` VARCHAR(255) DEFAULT NULL,
                                   `country` VARCHAR(255) DEFAULT NULL,
                                   `contact_email` VARCHAR(255) DEFAULT NULL,
                                   `phone_number` VARCHAR(255) DEFAULT NULL,
                                   `telephone_number` VARCHAR(255) DEFAULT NULL,
                                   `name` VARCHAR(255) DEFAULT NULL,
                                   `uuid` VARCHAR(255) NOT NULL,
                                   `last_modified_by` VARCHAR(255) DEFAULT NULL,
                                   `last_modified_date` datetime(6) DEFAULT NULL,
                                   PRIMARY KEY (`id`),
                                   UNIQUE KEY `UK_n78411th38cdhomne79rsow0o` (`uuid`),
                                   UNIQUE KEY `UKn78411th38cdhomne79rsow0o` (`uuid`)
)

CREATE TABLE IF NOT EXISTS `customer_customer_branches` (
                                              `customer_id` bigint NOT NULL,
                                              `customer_branches_id` bigint NOT NULL,
                                              PRIMARY KEY (`customer_id`,`customer_branches_id`),
                                              UNIQUE KEY `UK_20f1s8rs6p0d5v4w4a0ax3kql` (`customer_branches_id`),
                                              CONSTRAINT `FKbyvadfin602mvyxxwnb0ak7rc` FOREIGN KEY (`customer_branches_id`) REFERENCES `customer_branch` (`id`),
                                              CONSTRAINT `FKobs186pqeft6pxvm8eqqr7n37` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`)
)

CREATE TABLE IF NOT EXISTS `customer_service` (
                                    `id` bigint NOT NULL AUTO_INCREMENT,
                                    `created_by` VARCHAR(255) DEFAULT NULL,
                                    `created_date` datetime(6) DEFAULT NULL,
                                    `modified_by` VARCHAR(255) DEFAULT NULL,
                                    `modified_date` datetime(6) DEFAULT NULL,
                                    `status` VARCHAR(255) DEFAULT NULL,
                                    `version` bigint DEFAULT NULL,
                                    `customer_id` bigint DEFAULT NULL,
                                    `service_type_id` bigint DEFAULT NULL,
                                    `uuid` VARCHAR(255) NOT NULL,
                                    `last_modified_by` VARCHAR(255) DEFAULT NULL,
                                    `last_modified_date` datetime(6) DEFAULT NULL,
                                    PRIMARY KEY (`id`),
                                    UNIQUE KEY `UK_msi6jjftwbk64cx87hvbixllp` (`uuid`),
                                    UNIQUE KEY `UKmsi6jjftwbk64cx87hvbixllp` (`uuid`),
                                    KEY `FKkgf6lo6x392bcam3491xt4ye3` (`customer_id`),
                                    KEY `FK94xgxlhjvbt1ab2hqg3nbko3q` (`service_type_id`),
                                    CONSTRAINT `FK94xgxlhjvbt1ab2hqg3nbko3q` FOREIGN KEY (`service_type_id`) REFERENCES `service_type` (`id`),
                                    CONSTRAINT `FKkgf6lo6x392bcam3491xt4ye3` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`)
)

CREATE TABLE IF NOT EXISTS `customer_type` (
                                 `id` bigint NOT NULL AUTO_INCREMENT,
                                 `created_by` VARCHAR(255) DEFAULT NULL,
                                 `created_date` datetime(6) DEFAULT NULL,
                                 `modified_by` VARCHAR(255) DEFAULT NULL,
                                 `modified_date` datetime(6) DEFAULT NULL,
                                 `status` VARCHAR(255) DEFAULT NULL,
                                 `version` bigint DEFAULT NULL,
                                 `name` VARCHAR(255) NOT NULL,
                                 `uuid` VARCHAR(255) NOT NULL,
                                 `last_modified_by` VARCHAR(255) DEFAULT NULL,
                                 `last_modified_date` datetime(6) DEFAULT NULL,
                                 PRIMARY KEY (`id`),
                                 UNIQUE KEY `UK_jgmne8kshgm1k3ns20ot6yse4` (`name`),
                                 UNIQUE KEY `UKjgmne8kshgm1k3ns20ot6yse4` (`name`),
                                 UNIQUE KEY `UK_atax72lv09bx6vylj3cq2jx9h` (`uuid`),
                                 UNIQUE KEY `UKatax72lv09bx6vylj3cq2jx9h` (`uuid`)
)

CREATE TABLE IF NOT EXISTS `roles` (
                         `id` bigint NOT NULL AUTO_INCREMENT,
                         `created_by` VARCHAR(255) DEFAULT NULL,
                         `created_date` datetime(6) DEFAULT NULL,
                         `modified_by` VARCHAR(255) DEFAULT NULL,
                         `modified_date` datetime(6) DEFAULT NULL,
                         `status` VARCHAR(255) DEFAULT NULL,
                         `version` bigint DEFAULT NULL,
                         `name` VARCHAR(40) DEFAULT NULL,
                         `uuid` VARCHAR(255) NOT NULL,
                         `last_modified_by` VARCHAR(255) DEFAULT NULL,
                         `last_modified_date` datetime(6) DEFAULT NULL,
                         PRIMARY KEY (`id`)
)

CREATE TABLE IF NOT EXISTS `service_type` (
                                `id` bigint NOT NULL AUTO_INCREMENT,
                                `created_by` VARCHAR(255) DEFAULT NULL,
                                `created_date` datetime(6) DEFAULT NULL,
                                `modified_by` VARCHAR(255) DEFAULT NULL,
                                `modified_date` datetime(6) DEFAULT NULL,
                                `status` VARCHAR(255) DEFAULT NULL,
                                `version` bigint DEFAULT NULL,
                                `image_url` VARCHAR(255) DEFAULT NULL,
                                `name` VARCHAR(255) DEFAULT NULL,
                                `uuid` VARCHAR(255) NOT NULL,
                                `last_modified_by` VARCHAR(255) DEFAULT NULL,
                                `last_modified_date` datetime(6) DEFAULT NULL,
                                PRIMARY KEY (`id`),
                                UNIQUE KEY `UK_adwa29pmrvtcsq311jbi15emd` (`uuid`),
                                UNIQUE KEY `UKadwa29pmrvtcsq311jbi15emd` (`uuid`),
                                UNIQUE KEY `UK5xqxi6a47dld2eppt6hl3jl50` (`name`)
)

CREATE TABLE IF NOT EXISTS `user_account` (
                                `id` bigint NOT NULL AUTO_INCREMENT,
                                `created_by` VARCHAR(255) DEFAULT NULL,
                                `created_date` datetime(6) DEFAULT NULL,
                                `modified_by` VARCHAR(255) DEFAULT NULL,
                                `modified_date` datetime(6) DEFAULT NULL,
                                `status` VARCHAR(255) DEFAULT NULL,
                                `version` bigint DEFAULT NULL,
                                `email` VARCHAR(255) NOT NULL,
                                `enabled` VARCHAR(1) DEFAULT NULL,
                                `first_name` VARCHAR(50) NOT NULL,
                                `is_otp_required` bit(1) DEFAULT NULL,
                                `last_name` VARCHAR(50) NOT NULL,
                                `last_password_reset_date` datetime(6) DEFAULT NULL,
                                `password` VARCHAR(255) NOT NULL,
                                `password_reset_token` VARCHAR(255) DEFAULT NULL,
                                `user_name` VARCHAR(255) DEFAULT NULL,
                                `uuid` VARCHAR(255) NOT NULL,
                                `last_modified_by` VARCHAR(255) DEFAULT NULL,
                                `last_modified_date` datetime(6) DEFAULT NULL,
                                `role_id` bigint DEFAULT NULL,
                                `user_account_id` bigint DEFAULT NULL,
                                PRIMARY KEY (`id`),
                                UNIQUE KEY `UK_hl02wv5hym99ys465woijmfib` (`email`),
                                UNIQUE KEY `UKhl02wv5hym99ys465woijmfib` (`email`),
                                UNIQUE KEY `UK_piri22wyjhfc7odv6x0eyr7i6` (`uuid`),
                                UNIQUE KEY `UKpiri22wyjhfc7odv6x0eyr7i6` (`uuid`),
                                UNIQUE KEY `UK_n581kgbdmb1ruhd047l51wn0a` (`user_name`),
                                UNIQUE KEY `UKn581kgbdmb1ruhd047l51wn0a` (`user_name`),
                                KEY `FK7km135byyeyxob1l345ptmxc5` (`role_id`),
                                KEY `FKdetsil7lfrvq341room03mmpt` (`user_account_id`),
                                CONSTRAINT `FK7km135byyeyxob1l345ptmxc5` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),
                                CONSTRAINT `FKdetsil7lfrvq341room03mmpt` FOREIGN KEY (`user_account_id`) REFERENCES `user_account` (`id`)
)

CREATE TABLE IF NOT EXISTS `user_roles` (
                              `id` bigint NOT NULL AUTO_INCREMENT,
                              `created_by` VARCHAR(255) DEFAULT NULL,
                              `created_date` datetime(6) DEFAULT NULL,
                              `modified_by` VARCHAR(255) DEFAULT NULL,
                              `modified_date` datetime(6) DEFAULT NULL,
                              `status` VARCHAR(255) DEFAULT NULL,
                              `version` bigint DEFAULT NULL,
                              `role_id` bigint DEFAULT NULL,
                              `user_account_id` bigint DEFAULT NULL,
                              PRIMARY KEY (`id`),
                              KEY `FKh8ciramu9cc9q3qcqiv4ue8a6` (`role_id`),
                              KEY `FKmlpqbamr1miu4wq8s7rsbvjp4` (`user_account_id`),
                              CONSTRAINT `FKh8ciramu9cc9q3qcqiv4ue8a6` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),
                              CONSTRAINT `FKmlpqbamr1miu4wq8s7rsbvjp4` FOREIGN KEY (`user_account_id`) REFERENCES `user_account` (`id`)
)

